# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yeonguham' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yeonguham
  pod 'TagListView', '~> 1.0'
  pod 'Then'
  pod 'Alamofire', '~> 5.2'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Analytics'
  pod 'KakaoSDK'

end
